### ISSUE TITLE
FlashLFQ normalization issue

### ISSUE THREAD

**Issue by shrivastavabhishek** [smith-chem-wisc/FlashLFQ#109]
Hi @trishorts @lonelu 

I was running the FlashLFQ using cmd line and was expecting the normalised peptide intensity value in the QuantifiedPeptides.tsv file. I am sharing the parameters setting, PSM report file and experimental file here, please let me know what could be the missing steps here?
[Quantified_peptide_sample (1).xlsx](https://github.com/smith-chem-wisc/FlashLFQ/files/8309768/Quantified_peptide_sample.1.xlsx)
[Exp_Design_6_sample (1).txt](https://github.com/smith-chem-wisc/FlashLFQ/files/8309769/Exp_Design_6_sample.1.txt)
<img width="572" alt="flashLFQ_param" src="https://user-images.githubusercontent.com/43073252/159131831-c5b724ce-400c-4af6-a224-00be5d8d27ed.png">

**Comment by trishorts** [comment]
hello. it's not clear what error you are experiencing. can you describe the problem further?

**Comment by shrivastavabhishek** [comment]
Hi @trishorts I am running "Perform Bayesian protein fold-change analysis" in the flashlfq where S1 is the control and rest two are treatment groups, mentioned in the experimental file. I have also set the parameter as mentioned (attached screenshot). Here my concern is that I am not getting the normalised intensity values for all the samples, column number 6 onwards to 12 in the QuantifiedPeptides.tsv file. I am getting all the raw intensity values. Please have a look into attached [screenshot.]
<img width="494" alt="raw_intensity_flashlfq" src="https://user-images.githubusercontent.com/43073252/159466600-1320c833-d2c0-4edc-8e1b-6824fa004628.png">

Please let me know if you need more information about it.

**Comment by rmillikin** [comment]
Hi @shrivastavabhishek ,

Intensity normalization corrects for systematic differences in intensities between samples. It makes the median difference in intensities between two samples equal to zero. So these numbers look like they could be normalized to me. Do you mean you want log2-transformed values? Or log fold-changes between samples?

The Bayesian protein quant only computes fold-changes at the protein level, not the peptide level, also.

**Comment by shrivastavabhishek** [comment]
Hi @rmillikin Thanks for reply. Yes, I would like to get log2-transformed values, Please let me know how to acheive that.
It would be a great help.

Thanks
Abhishek

**Comment by rmillikin** [comment]
Currently, there isn't an option in FlashLFQ to report log intensities; you'll have to log these yourself (for example, in Excel, Perseus, etc.).
