### ISSUE TITLE
Enquiry on where the actual namespace for FlashLFQ exists

### ISSUE THREAD

**Issue by acquayefrank** [smith-chem-wisc/FlashLFQ#124]
Hello,
I was reading the code for FlashLFQ, and I realized I couldn't find where the actual FlashLFQ namespace was created.
Please point me to where I can find the namespace of FlashLFQ.
Kind Regards

**Comment by trishorts** [comment]
Ha. Sorry. A bit of a bait and switch. FlashLFQ here is a bit of a user interface. the actual meat of FlashLFQ is in our MS utility software mzlib. Here is a link to the FlashLFQ code in mzlib: Let me know if you find it okay and if you need any help looking it over.
https://github.com/smith-chem-wisc/mzLib/tree/master/mzLib/FlashLFQ

**Comment by acquayefrank** [comment]
Thank you for the information.
