### ISSUE TITLE
possible bug in latest release with `--rmc` behavior

### ISSUE THREAD

**Issue by jvolkening** [smith-chem-wisc/FlashLFQ#149]
Using the latest release (2.0.0), it seems `--rmc` does not behave as previously.

**Expected behavior:** When `--rmc true` is given, samples without at least one matching PSM within the condition will not be assigned intensities by MBR.

**Observed behavior:** For example, a few lines selected from `QuantifiedPeptides.tsv`:

|Sequence|Base Sequence|Protein Groups|Gene Names|Organism|Intensity_1874C5-A|Intensity_1874C5-B|Intensity_1874C5-C|Intensity_LV-A|Intensity_LV-B|Intensity_LV-C|Intensity_mock-A|Intensity_mock-B|Intensity_mock-C|Detection Type_1874C5-A|Detection Type_1874C5-B|Detection Type_1874C5-C|Detection Type_LV-A|Detection Type_LV-B|Detection Type_LV-C|Detection Type_mock-A|Detection Type_mock-B|Detection Type_mock-C|
|--------|-------------|--------------|----------|--------|------------------|------------------|------------------|--------------|--------------|--------------|----------------|----------------|----------------|-----------------------|-----------------------|-----------------------|-------------------|-------------------|-------------------|---------------------|---------------------|---------------------|
|ALGSNVPR|ALGSNVPR|US5|||4650176.15625|10562500.949712902|7968988.740985767|31414398.365905236|28745135.034564063|49140023.99963495|0|776319.2995175337|3076354.445115193|MBR|MSMS|MBR|MSMS|MSMS|MSMS|NotDetected|MBR|MBR|
|ATQTPSTEPEVLTQSPSTEPVPFTR|ATQTPSTEPEVLTQSPSTEPVPFTR|US5|||3869611.7604166665|2575927.9341527303|6607324.32429818|9727888.426961571|8882067.396104535|9277100.016584055|0|0|2551998.33661184|MSMS|MSMS|MSMS|MSMS|MSMS|MSMS|NotDetected|NotDetected|MBR|

The last three samples are mock treatments, and are assigned as such in `ExperimentalDesign.txt`. There are no PSMs for the peptides shown in those samples, as expected since the protein should not be present in those treatments. Nevertheless, they are assigned intensities based on MBR.

I did not see this behavior in the previous version I ran (1.2.6) -- all worked as expected.

I am running on Linux and the exact command used for both versions was:

```bash
dotnet flashlfq/CMD.dll --idt combined_flashLFQ_input.min005.tsv --rep mzml --nor true --out . --mrt 1.5 --ppm 5 --rmc true
```

**Comment by trishorts** [comment]
if you could make the data available, we could have a look. box folder works if you have one.

**Comment by jvolkening** [comment]
Don't think I can share the full datasets, but I'll try to put together a MWE.

**Comment by Alexander-Sol** [comment]
One point of correction: When -rmc is true, samples without at least one PSM linked to the same protein group are not considered for MBR. If **any** US5 peptides were detected in the mock conditions, then **all** US5 peptides are considered valid MBR donors.

**Comment by jvolkening** [comment]
@Alexander-Sol thanks for the explanation, I didn't understand that to be the case. In my mind this is less useful, but I understand that's a matter of viewpoint or use case.

I'm still fairly sure that the behavior between 1.2.6 and 2.0.0 is different, but I will do some more testing with your explanation in mind.

**Comment by jvolkening** [comment]
> If **any** US5 peptides were detected in the mock conditions, then **all** US5 peptides are considered valid MBR donors.

It looks like this explains the results I'm looking at, thanks. Although I need to do this as the peptide rather than protein group level, I can post-process the results to achieve the same effect.
