### ISSUE TITLE
FlashLFQ.FlashLFQEngine.RetentionTimeCalibrationAndErrorCheckMatchedFeatures  FATAL UNHANDLED EXCEPTION

### ISSUE THREAD

**Issue by jj-umn** [smith-chem-wisc/FlashLFQ#41]
I'm not sure if this is an error in my run of FlashLFQ or if this just happened to have an empty list.

(__flashlfq@0.1.102) galaxy@galaxy [~/tmp/test] % ln -s '/panfs/roc/risdb/galaxy/libdata/proteomics/UW/PASS00470/Mouse_XML/B6.PSMs.tsv' 'B6.PSMs.psmtsv' && mkdir spectrum_dir && ln -s '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/190/dataset_190425.dat' 'spectrum_dir/04-29-13_B6_Frac1_9uL.mzML' && ln -s '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/190/dataset_190426.dat' 'spectrum_dir/04-29-13_B6_Frac2_9p5uL.mzML' && ln -s '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/190/dataset_190427.dat' 'spectrum_dir/04-29-13_B6_Frac3_9p5uL.mzML' && ln -s '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/190/dataset_190428.dat' 'spectrum_dir/04-29-13_B6_Frac4_8uL.mzML' && ln -s '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/190/dataset_190429.dat' 'spectrum_dir/04-29-13_B6_Frac5_4uL.mzML' && ln -s '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/190/dataset_190430.dat' 'spectrum_dir/04-29-13_B6_Frac6_5uL.mzML' && ln -s '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/190/dataset_190431.dat' 'spectrum_dir/04-29-13_B6_Frac7_5uL.mzML' && ln -s '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/190/dataset_190432.dat' 'spectrum_dir/04-29-13_B6_Frac8_9p5uL.mzML' && ln -s '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/190/dataset_190433.dat' 'spectrum_dir/04-29-13_B6_Frac9_9p5uL.mzML' &&  FlashLFQ --idt 'B6.PSMs.psmtsv' --rep spectrum_dir --ppm 10.0 --iso 5.0 --nis 2 --rmm true --mbr true --pau false && cat *_FlashLFQ_Log.txt | sed 's/\(Analysis summary for:\).*working./\1 /' > '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/196/dataset_196360.dat' && cp *_FlashLFQ_QuantifiedBaseSequences.tsv '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/196/dataset_196362.dat' && cp *_FlashLFQ_QuantifiedModifiedSequences.tsv '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/196/dataset_196363.dat' && cp *_FlashLFQ_QuantifiedPeaks.tsv '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/196/dataset_196361.dat' && grep -v '^test$' *_FlashLFQ_QuantifiedProteins.tsv > '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/files/000/196/dataset_196364.dat'
Opening PSM file B6.PSMs.psmtsv
Done reading PSMs
Setup is OK - running FlashLFQ engine
Assigning MS1 peaks to bins
Quantifying peptides for 04-29-13_B6_Frac7_5uL
Finding possible matched peptides for 04-29-13_B6_Frac7_5uL
Checking errors
Finished 04-29-13_B6_Frac7_5uL
Assigning MS1 peaks to bins
Quantifying peptides for 04-29-13_B6_Frac1_9uL
Finding possible matched peptides for 04-29-13_B6_Frac1_9uL
Checking errors
Finished 04-29-13_B6_Frac1_9uL
Assigning MS1 peaks to bins
Quantifying peptides for 04-29-13_B6_Frac3_9p5uL
Finding possible matched peptides for 04-29-13_B6_Frac3_9p5uL
Checking errors
Finished 04-29-13_B6_Frac3_9p5uL
Assigning MS1 peaks to bins
Quantifying peptides for 04-29-13_B6_Frac4_8uL
Finding possible matched peptides for 04-29-13_B6_Frac4_8uL
Checking errors
Finished 04-29-13_B6_Frac4_8uL
Assigning MS1 peaks to bins
Quantifying peptides for 04-29-13_B6_Frac8_9p5uL
Finding possible matched peptides for 04-29-13_B6_Frac8_9p5uL
Checking errors
Finished 04-29-13_B6_Frac8_9p5uL
Assigning MS1 peaks to bins
Quantifying peptides for 04-29-13_B6_Frac6_5uL
Finding possible matched peptides for 04-29-13_B6_Frac6_5uL
Checking errors
Finished 04-29-13_B6_Frac6_5uL
Assigning MS1 peaks to bins
Quantifying peptides for 04-29-13_B6_Frac2_9p5uL
Finding possible matched peptides for 04-29-13_B6_Frac2_9p5uL
Checking errors
Finished 04-29-13_B6_Frac2_9p5uL
Assigning MS1 peaks to bins
Quantifying peptides for 04-29-13_B6_Frac9_9p5uL
Finding possible matched peptides for 04-29-13_B6_Frac9_9p5uL
Checking errors
Finished 04-29-13_B6_Frac9_9p5uL
Assigning MS1 peaks to bins
Quantifying peptides for 04-29-13_B6_Frac5_4uL
Finding possible matched peptides for 04-29-13_B6_Frac5_4uL
Checking errors
Finished 04-29-13_B6_Frac5_4uL
Running retention time calibration

Unhandled Exception:
System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.Average (System.Collections.Generic.IEnumerable`1[T] source) [0x0006a] in <5f01f5aacbb346938d6f9b4e69d4383a>:0 
  at FlashLFQ.FlashLFQEngine.RetentionTimeCalibrationAndErrorCheckMatchedFeatures () [0x00436] in <e213ab8aae014a9999378ef2acd8f5fc>:0 
  at FlashLFQ.FlashLFQEngine.Run () [0x002cb] in <e213ab8aae014a9999378ef2acd8f5fc>:0 
  at FlashLFQExecutable.FlashLFQExecutable.Main (System.String[] args) [0x00547] in <5426307fba1e49e7a0c9affc907f11d0>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.Average (System.Collections.Generic.IEnumerable`1[T] source) [0x0006a] in <5f01f5aacbb346938d6f9b4e69d4383a>:0 
  at FlashLFQ.FlashLFQEngine.RetentionTimeCalibrationAndErrorCheckMatchedFeatures () [0x00436] in <e213ab8aae014a9999378ef2acd8f5fc>:0 
  at FlashLFQ.FlashLFQEngine.Run () [0x002cb] in <e213ab8aae014a9999378ef2acd8f5fc>:0 
  at FlashLFQExecutable.FlashLFQExecutable.Main (System.String[] args) [0x00547] in <5426307fba1e49e7a0c9affc907f11d0>:0 
(__flashlfq@0.1.102) galaxy@galaxy [~/tmp/test] %

**Comment by trishorts** [comment]
We'll have a look jj. Anything more that you could tell us about your run might help the debug.

**Comment by rmillikin** [comment]
Thanks - the error is specific enough that I can probably track it down. I'll check this out today and get back to you

**Comment by rmillikin** [comment]
I suspect I've found the problem; the retention time calibration tries to match common peaks between runs, but I'm guessing since your data is fractionated, there is at least one fraction that shares no peptides in common with one other file, resulting in the unintended crash. I think this should be fairly simple to resolve; are you able to share your files in the cloud? This would help me test my fix. You can email me the link (rmillikin at wisc dot edu). Thanks!

**Comment by rmillikin** [comment]
I think I've fixed this crash in 0.1.103; please let me know if it recurs. Apologies for the delay, we're putting out some fires in MetaMorpheus too.

**Comment by rmillikin** [comment]
I'm going to close this, feel free to reopen if you encounter the same problem (or open a new issue)
