### ISSUE TITLE
Error in running FlashLFQ on a server

### ISSUE THREAD

**Issue by cksakura** [smith-chem-wisc/FlashLFQ#43]
Hello,

I encountered an exception when I was running FlashLFQ in a server with a Windows Server 2008 system. Below are the details:

 Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.IO.FileNotFoundException: Could not load file or assembly 'System.Value
Tuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one
 of its dependencies. The system cannot find the file specified.
   at FlashLFQ.FlashLFQEngine.FilterPeaksByIsotopicDistribution(IEnumerable`1 pe
aks, Identification identification, Int32 chargeState, Boolean lookForBadIsotope
, Dictionary`2 allMs1Scans)
   at FlashLFQ.FlashLFQEngine.<>c__DisplayClass31_0.<QuantifyMS2IdentifiedPeptid
es>b__4(Tuple`2 range, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEac
hWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating
>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](P
artitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Actio
n`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal,
 Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, Par
allelOptions parallelOptions, Action`2 body)
   at FlashLFQ.FlashLFQEngine.QuantifyMS2IdentifiedPeptides(RawFileInfo fileInfo
, Dictionary`2 mzBins, Dictionary`2 allMs1Scans)
   at FlashLFQ.FlashLFQEngine.Run()
   at FlashLFQExecutable.FlashLFQExecutable.Main(String[] args) in C:\Users\rmil
likin\Source\Repos\FlashLFQ_Master\FlashLFQ Executable\FlashLFQExecutable.cs:lin
e 98

The system and software information are below:

![error_flashlfq_2](https://user-images.githubusercontent.com/6902434/36984578-393a14d8-2063-11e8-828f-8de38459b46e.jpg)
![error_flashlfq_1](https://user-images.githubusercontent.com/6902434/36984591-3fa1a3ea-2063-11e8-8965-138012df7851.jpg)

FlashLFQ runs well on my computer (windows 10 system), but when I'm quantifying 24 raw files and set the --mbr as true, it was totally stuck after about 14-15 files were finished. I'm also wondering if I'd like to quantifying about 20-30 raw files simultaneously, what's the recommended hardware environment?

Thank you for your time.

**Comment by rmillikin** [comment]
Hello,

I recently fixed a crash (related to System.ValueTuple) in version 0.1.102. Can you double check that you're using version 0.1.102 or 0.1.103? If you are, the problem may be with your .NET framework version. Try updating to version [4.7.1](https://www.microsoft.com/net/download/dotnet-framework-runtime). If neither of those work I can investigate further.

Match-between-runs is in an early state and is currently very RAM intensive. Significant enhancements in terms of performance and quality will be coming in the coming months. For reference my machine has 32GB RAM which is able to handle 20 files with match-between-runs enabled.

Thanks,
Rob

**Comment by cksakura** [comment]
Hello,

Thank you for your response. I'm using the version 0.1.102. I'll check the
version of the .NET framework.
I'll turn off --mbr for the processing of my dataset.
Thank you again for your help.

Best regards,

Kai

**Comment by rmillikin** [comment]
Hello Kai, 

Were you able to get FlashLFQ working with the updated .NET framework?

Rob

**Comment by cksakura** [comment]
Hello Rob,

I'm sorry that I didn't have an opportunity to test it. In our lab we use a
public server, which is very busy in these days. I didn't have an
opportunity to update the .NET framework and restart the machine.
Now I run FlashLFQ on my PC and it works very well.
Thank you for your help.

Best regards,

Kai

**Comment by rmillikin** [comment]
Ok, no worries about the .NET version. I was just curious. Glad to hear FlashLFQ is working well. I will hopefully be making MBR more RAM-efficient soon.
