### ISSUE TITLE
Question about protein quantitative inference

### ISSUE THREAD

**Issue by yishai99** [smith-chem-wisc/FlashLFQ#59]
Hi,
Can you tell us how you infer the protein quantity from the peptides? Do you sum the peptide intensities? Is it Hi-3? Did you use the way MaxQuant do it?
Thanks,

Yishai

**Comment by rmillikin** [comment]
In the current standalone version of FlashLFQ, it's the sum of the peptide intensities, and shared peptides are split between the proteins that share them. It will soon be changed to top3 in a few weeks.

The current FlashLFQ version wrapped into MetaMorpheus is top3.

In the longer-term, I want to use something similar to Diffacto, but this will probably take a while (a few months) to get right.

**Comment by yishai99** [comment]
Thanks for the info.
We found MaxQuant’s solution to this to be very successful, as described in this paper <http://www.mcponline.org/content/13/9/2513.short>. Figure 2 of the paper describes the method. I hope you consider this instead of the Hi-3.
Also, I strongly advice (ask?) that you include the following options: 1. choose to quantify based on all peptides, razor+unique, just unique. 2. choose whether or not to include modified peptides in the protein quan. This is particularly important in MM since it identified so many PTMs and they tend to have more missing values.

Thanks,

Yishai

**Comment by rmillikin** [comment]
I've added a protein quant system that uses Bayesian statistics as of v1.0.0 :) You can read about it here: https://github.com/smith-chem-wisc/FlashLFQ/wiki/Bayesian-Protein-Fold-Change-Analysis
