### ISSUE TITLE
linux absolute paths don't work

### ISSUE THREAD

**Issue by jvolkening** [smith-chem-wisc/FlashLFQ#71]
FlashLFQ on Linux doesn't seem to like absolute filepaths:
```
Invalid arguments - type "--help" for valid arguments
```
I suspect this is related to fclp/fluent-command-line-parser#42. Using the modification suggested at the end of that issue may solve this once FCLP 1.5 is available. In the meantime, it may be worth mentioning in the README. Relative paths work just fine on Linux.

**Comment by rmillikin** [comment]
Thanks for the report and investigation! I'll add that to the Readme.

**Comment by rmillikin** [comment]
FCLP looks like it hasn't been updated in a year. I doubt 1.5 is coming out anytime soon. I'll hunt around and see if I can find another option to use.

**Comment by rmillikin** [comment]
Fixed in version 1.0.1
