### ISSUE TITLE
format input to allow pfind results

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/FlashLFQ#75]
File_Name	Scan_No	Exp.MH+	Charge	Q-value	Sequence	Calc.MH+	Mass_Shift(Exp.-Calc.)	Raw_Score	Final_Score	Modification	Specificity	Proteins	Positions	Label	Target/Decoy	Miss.Clv.Sites	Avg.Frag.Mass.Shift	Others
QEPlus2_05042018_12_YY2.45169.45169.4.0.dta	45169	3121.401119	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3121.395466	0.005653	34.984453	1.18871e-009	10,Deamidated[N];17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|0|	target	0	1.569639	22027004	0	0	0	33554422	0	0	0	36
QEPlus2_05042018_12_YY2.44527.44527.4.0.dta	44527	3120.412257	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3120.411450	0.000807	32.991729	1.4656e-009	17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|	target	0	0.474375	7908	0	0	0	33554428	0	0	0	36
QEPlus2_05042018_6_X1.13283.13283.2.0.dta	13283	2383.953905	2	0	GGGGGGYGSGGSSYGSGGGSYGSGGGGGGGR	2383.951741	0.002164	35.872558	2.31698e-009		3	sp|P04264|K2C1_HUMAN/	518,R,G/	1|	target	0	0.401425	33554424	0	0	0	1073741823	0	0	0	0
QEPlus2_05042018_12_YY2.44927.44927.4.0.dta	44927	3121.407331	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3121.395466	0.011865	34.343263	2.33793e-009	10,Deamidated[N];17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|0|	target	0	1.420738	4284148	0	0	0	33554422	0	0	0	100
QEPlus2_05042018_12_YY2.49313.49313.3.0.dta	49313	2635.375994	3	0	LISPESTVMLLEAQAATGGIIDPHR	2635.375852	0.000142	32.448126	2.64366e-009	9,Oxidation[M];	3	sp|P15924|DESP_HUMAN/	2038,K,N/	1|0|	target	0	0.110548	32694	0	0	0	8388574	0	0	0	36
QEPlus2_05042018_12_YY2.45087.45087.4.0.dta	45087	3121.402781	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3121.395466	0.007315	33.260955	3.79759e-009	10,Deamidated[N];17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|0|	target	0	1.671968	5250804	0	0	0	33554422	0	0	0	36
QEPlus2_05042018_12_YY2.45008.45008.4.0.dta	45008	3121.401347	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3121.395466	0.005881	33.065695	3.97715e-009	10,Deamidated[N];17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|0|	target	0	1.299155	1055996	0	0	0	33554420	0	0	0	36
QEPlus2_05042018_12_YY2.45631.45631.2.0.dta	45631	2228.118254	2	0	AKLEAAVAEAEQQGEAALSDAR	2228.115223	0.003031	30.403223	4.89721e-009		3	sp|P78386|KRT85_HUMAN/tr|F5GYI5|F5GYI5_HUMAN/	360,R,C/148,R,C/	1|	target	1	1.467041	786430	0	0	0	2097151	0	0	0	0
QEPlus2_05042018_12_YY2.45556.45556.2.0.dta	45556	2228.119265	2	0	AKLEAAVAEAEQQGEAALSDAR	2228.115223	0.004042	30.423535	5.15757e-009		3	sp|P78386|KRT85_HUMAN/tr|F5GYI5|F5GYI5_HUMAN/	360,R,C/148,R,C/	1|	target	1	2.164531	1835006	0	0	0	2097151	0	0	0	0
QEPlus2_05042018_12_YY2.39788.39788.2.0.dta	39788	2726.326707	2	0	QITSGPSAIGGSITVVAPDSCAPCQPR	2726.323501	0.003206	27.620032	1.10592e-008	21,Carbamidomethyl[C];24,Carbamidomethyl[C];	3	sp|P78386|KRT85_HUMAN/tr|F5GYI5|F5GYI5_HUMAN/	465,R,S/253,R,S/	1|0|0|	target	0	0.348042	19004894	0	0	0	33554430	0	0	0	36
QEPlus2_05042018_12_YY2.44603.44603.4.1.dta	44603	3120.412690	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3120.411450	0.001240	30.134968	1.12488e-008	17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|	target	0	0.275210	530148	0	0	0	33554420	0	0	0	36
QEPlus2_05042018_12_YY2.44842.44842.4.1.dta	44842	3120.417818	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3120.411450	0.006368	30.973896	1.18232e-008	17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|	target	0	0.614369	1578980	0	0	0	33554373	0	0	0	36
QEPlus2_05042018_10_YY3.44367.44367.4.1.dta	44367	3121.407147	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3121.395466	0.011681	36.644597	1.24892e-008	10,Deamidated[N];17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|0|	target	0	1.631976	5261564	0	0	0	33554422	0	0	0	100
QEPlus2_05042018_12_YY2.39861.39861.2.0.dta	39861	2726.328600	2	0	QITSGPSAIGGSITVVAPDSCAPCQPR	2726.323501	0.005099	27.598331	1.29406e-008	21,Carbamidomethyl[C];24,Carbamidomethyl[C];	3	sp|P78386|KRT85_HUMAN/tr|F5GYI5|F5GYI5_HUMAN/	465,R,S/253,R,S/	1|0|0|	target	0	1.953556	19267070	0	0	0	33554430	0	0	0	36
QEPlus2_05042018_12_YY2.39708.39708.2.0.dta	39708	2726.326054	2	0	QITSGPSAIGGSITVVAPDSCAPCQPR	2726.323501	0.002553	26.999267	1.57851e-008	21,Carbamidomethyl[C];24,Carbamidomethyl[C];	3	sp|P78386|KRT85_HUMAN/tr|F5GYI5|F5GYI5_HUMAN/	465,R,S/253,R,S/	1|0|0|	target	0	0.214438	19004926	0	0	0	33554430	0	0	0	36
QEPlus2_05042018_12_YY2.30113.30113.3.0.dta	30113	3344.429584	3	0	GEPTSCQPVHCETGNLETSCGSSTAYYVPR	3344.425124	0.004460	30.752626	1.58404e-008	6,Carbamidomethyl[C];11,Carbamidomethyl[C];20,Carbamidomethyl[C];	1	sp|Q6PEX3|KR261_HUMAN/	60,C,P/	1|0|0|0|	target	0	0.363459	152043132	0	0	0	268431834	0	0	0	36
QEPlus2_05042018_10_YY3.44900.44900.4.0.dta	44900	3121.396576	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3121.395466	0.001110	35.305410	1.73756e-008	10,Deamidated[N];17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|0|	target	0	1.826215	1122036	0	0	0	33554420	0	0	0	36
QEPlus2_05042018_12_YY2.44742.44742.4.2.dta	44742	3120.416308	4	0	VLDPEDYGPNGLDIEWMQVNSDPAHHR	3120.411450	0.004858	29.993634	1.77656e-008	17,Oxidation[M];	1	sp|P0DPA2|VSIG8_HUMAN/	46,Y,E/	1|0|	target	0	-0.369678	7652	0	0	0	33554400	0	0	0	36
QEPlus2_05042018_12_YY2.39938.39938.2.0.dta	39938	2726.330625	2	0	QITSGPSAIGGSITVVAPDSCAPCQPR	2726.323501	0.007124	27.035905	1.97542e-008	21,Carbamidomethyl[C];24,Carbamidomethyl[C];	3	sp|P78386|KRT85_HUMAN/tr|F5GYI5|F5GYI5_HUMAN/	465,R,S/253,R,S/	1|0|0|	target	0	0.508439	2227678	0	0	0	33554430	0	0	0	36

**Comment by rmillikin** [comment]
merged with #80
