### ISSUE TITLE
Undetermined issue with peak detection?

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/FlashLFQ#77]
Hi guys,

So I've ran the software against some data I've got from Byonic. despite seeing good peaks in the raw files, I get "Identified and not quantified" or "Not detected" in the output.
The only thing I'm not sure about is the monoisotopic mass - is it the deconvoluted one? if not should I add to the ID table the same sequence with other isotopes? 
please let me know if you'd like any files. 

Thanks!
D.

**Comment by rmillikin** [comment]
The monoisotopic mass should be the theoretical mass - is that what you mean?

If you can share the files with us, that would be a good way to solve this I think. Can you email me a link to spectra/PSM files?
